# config.py

CAMERA_INDEX = 0
DETECTION_CONF = 0.75
TRACKING_CONF = 0.75

GESTURE_COOLDOWN = 1.5
SWIPE_COOLDOWN = 0.8
ZOOM_COOLDOWN = 0.5

GESTURE_HOLD_FRAMES = 8
SWIPE_THRESHOLD = 90
SWIPE_WINDOW = 0.5

PINCH_OPEN_DIST = 80
PINCH_CLOSE_DIST = 30
PINCH_HISTORY = 5

PROCESS_EVERY_N_FRAMES = 2